//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtuoso.Roamie.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class WindowsAccountSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WindowsAccountSettings defaultInstance = ((WindowsAccountSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowsAccountSettings())));
        
        public static WindowsAccountSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public global::Virtuoso.Roamie.Configuration.ConfigurationPersistencyMode ConfigurationPersitencyMode {
            get {
                return ((global::Virtuoso.Roamie.Configuration.ConfigurationPersistencyMode)(this["ConfigurationPersitencyMode"]));
            }
            set {
                this["ConfigurationPersitencyMode"] = value;
            }
        }
    }
}
