//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtuoso.Roamie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Virtuoso.Roamie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ftp provider: ftp://my.com/dir/myDatabase.dat {0}Http provider: http://my.com/dir/myDatabase.dat.
        /// </summary>
        internal static string Balloon_Text_Examples_NL1 {
            get {
                return ResourceManager.GetString("Balloon_Text_Examples_NL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name: {1} {0}Database provider: {2} {0}Remote path: {3} .
        /// </summary>
        internal static string Balloon_Text_ProfileToolTip_NL1 {
            get {
                return ResourceManager.GetString("Balloon_Text_ProfileToolTip_NL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will not be propagated to your roaming database..
        /// </summary>
        internal static string Balloon_Text_SandboxActivated {
            get {
                return ResourceManager.GetString("Balloon_Text_SandboxActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta merge recommended.
        /// </summary>
        internal static string Balloon_Title_DeltaMergeRecommended {
            get {
                return ResourceManager.GetString("Balloon_Title_DeltaMergeRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta synchronization warning.
        /// </summary>
        internal static string Balloon_Title_DeltaWarning {
            get {
                return ResourceManager.GetString("Balloon_Title_DeltaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string Balloon_Title_Examples {
            get {
                return ResourceManager.GetString("Balloon_Title_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database will not be updated.
        /// </summary>
        internal static string Balloon_Title_SandboxActivated {
            get {
                return ResourceManager.GetString("Balloon_Title_SandboxActivated", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CbtnIcon_Delete {
            get {
                object obj = ResourceManager.GetObject("CbtnIcon_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Config_General {
            get {
                return ResourceManager.GetString("Config_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Config_General_About {
            get {
                return ResourceManager.GetString("Config_General_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Roamie copyright information..
        /// </summary>
        internal static string Config_General_About_Description {
            get {
                return ResourceManager.GetString("Config_General_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviour.
        /// </summary>
        internal static string Config_General_Behaviour {
            get {
                return ResourceManager.GetString("Config_General_Behaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Roamie&apos;s behaviour..
        /// </summary>
        internal static string Config_General_Behaviour_Description {
            get {
                return ResourceManager.GetString("Config_General_Behaviour_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure general settings of Roamie..
        /// </summary>
        internal static string Config_General_Description {
            get {
                return ResourceManager.GetString("Config_General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string Config_General_Proxy {
            get {
                return ResourceManager.GetString("Config_General_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Roamie to use a proxy..
        /// </summary>
        internal static string Config_General_Proxy_Description {
            get {
                return ResourceManager.GetString("Config_General_Proxy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaming profiles.
        /// </summary>
        internal static string Config_RoamingProfiles {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto profile.
        /// </summary>
        internal static string Config_RoamingProfiles_DefaultProfile {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure a profile to be automatically used on the startup..
        /// </summary>
        internal static string Config_RoamingProfiles_DefaultProfile_Description {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_DefaultProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, remove or modify existing roaming profiles..
        /// </summary>
        internal static string Config_RoamingProfiles_Description {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Config_RoamingProfiles_Manage {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify or remove an existing profile..
        /// </summary>
        internal static string Config_RoamingProfiles_Manage_Description {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_Manage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile.
        /// </summary>
        internal static string Config_RoamingProfiles_NewProfile {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new roaming profile..
        /// </summary>
        internal static string Config_RoamingProfiles_NewProfile_Description {
            get {
                return ResourceManager.GetString("Config_RoamingProfiles_NewProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the roaming configuration. .
        /// </summary>
        internal static string ExceptionMsg_ConfigurationLoadFailure {
            get {
                return ResourceManager.GetString("ExceptionMsg_ConfigurationLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the roaming configuration. Your settings may not be lost..
        /// </summary>
        internal static string ExceptionMsg_ConfigurationSaveFailure {
            get {
                return ResourceManager.GetString("ExceptionMsg_ConfigurationSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A contact without the sync token was detected. Contact Roamie&apos;s author..
        /// </summary>
        internal static string ExceptionMsg_ContactWithoutTokenFound {
            get {
                return ResourceManager.GetString("ExceptionMsg_ContactWithoutTokenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delta manifest token differs from the one of the currently loaded database..
        /// </summary>
        internal static string ExceptionMsg_DbTokenMismatch {
            get {
                return ResourceManager.GetString("ExceptionMsg_DbTokenMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while merging a delta with the database..
        /// </summary>
        internal static string ExceptionMsg_DeltaMergeFailed {
            get {
                return ResourceManager.GetString("ExceptionMsg_DeltaMergeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some database changes present in the delta could not be applied..
        /// </summary>
        internal static string ExceptionMsg_DeltaNotAppliedCompletely {
            get {
                return ResourceManager.GetString("ExceptionMsg_DeltaNotAppliedCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while performing the delta synchronization..
        /// </summary>
        internal static string ExceptionMsg_DeltaSyncFailed {
            get {
                return ResourceManager.GetString("ExceptionMsg_DeltaSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while decrypting the database. Wrong database password or corrupted data. {0}.
        /// </summary>
        internal static string ExceptionMsg_Formatable1_CryptoError {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_CryptoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while synchronizing local database. {0}.
        /// </summary>
        internal static string ExceptionMsg_Formatable1_GeneralDownloadError {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_GeneralDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while synchronizing remote database. {0}.
        /// </summary>
        internal static string ExceptionMsg_Formatable1_GeneralUploadError {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable1_GeneralUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network error occured while downloading the database from {0}. {1}.
        /// </summary>
        internal static string ExceptionMsg_Formatable2_DownloadError {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable2_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected server response received. Received {0}, but expected {1}..
        /// </summary>
        internal static string ExceptionMsg_Formatable2_UnexpectedResponse {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable2_UnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network error occured while uploading the database to {0}. {1}.
        /// </summary>
        internal static string ExceptionMsg_Formatable2_UploadError {
            get {
                return ResourceManager.GetString("ExceptionMsg_Formatable2_UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the synchronization..
        /// </summary>
        internal static string ExceptionMsg_GeneralSyncException {
            get {
                return ResourceManager.GetString("ExceptionMsg_GeneralSyncException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote file is empty..
        /// </summary>
        internal static string ExceptionMsg_RemoteFileIsEmpty {
            get {
                return ResourceManager.GetString("ExceptionMsg_RemoteFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote host url protocol is not supported by this provider..
        /// </summary>
        internal static string ExceptionMsg_RemoteUriNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMsg_RemoteUriNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization test failed. Check the supplied credentials..
        /// </summary>
        internal static string ExceptionMsg_SyncTestFailed {
            get {
                return ResourceManager.GetString("ExceptionMsg_SyncTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization test failed, remote database not found. Check the remote address..
        /// </summary>
        internal static string ExceptionMsg_SyncTestFailed_NotFound {
            get {
                return ResourceManager.GetString("ExceptionMsg_SyncTestFailed_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while downloading a delta. Verify whether all deltas are present and available..
        /// </summary>
        internal static string ExceptionMsg_UnableToDownloadDelta {
            get {
                return ResourceManager.GetString("ExceptionMsg_UnableToDownloadDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a database driver. Database driver files must be named like dbx_*.dll or *.dbx..
        /// </summary>
        internal static string ExceptionMsg_UnableToFindDbDriver {
            get {
                return ResourceManager.GetString("ExceptionMsg_UnableToFindDbDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize delta engine. Delta manifest may be corrupted or cannot be retrieved - .
        /// </summary>
        internal static string ExceptionMsg_UnableToInitDeltaEngine {
            get {
                return ResourceManager.GetString("ExceptionMsg_UnableToInitDeltaEngine", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Header_Golden {
            get {
                object obj = ResourceManager.GetObject("Header_Golden", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_193 {
            get {
                object obj = ResourceManager.GetObject("Icon_193", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_228_16x16 {
            get {
                object obj = ResourceManager.GetObject("Icon 228_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_237 {
            get {
                object obj = ResourceManager.GetObject("Icon_237", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_244_256x256_Trans {
            get {
                object obj = ResourceManager.GetObject("Icon 244_256x256_Trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_244_48x48 {
            get {
                object obj = ResourceManager.GetObject("Icon 244_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_292 {
            get {
                object obj = ResourceManager.GetObject("Icon_292", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_16x16_Delete {
            get {
                object obj = ResourceManager.GetObject("Image_16x16_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_16x16_Profile {
            get {
                object obj = ResourceManager.GetObject("Image_16x16_Profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_16x16_Users {
            get {
                object obj = ResourceManager.GetObject("Image_16x16_Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24x24_Add {
            get {
                object obj = ResourceManager.GetObject("Image_24x24_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24x24_Computer {
            get {
                object obj = ResourceManager.GetObject("Image_24x24_Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24x24_Download {
            get {
                object obj = ResourceManager.GetObject("Image_24x24_Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_24x24_Web {
            get {
                object obj = ResourceManager.GetObject("Image_24x24_Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Active {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Add {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Computer {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Disabled {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Edit {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Favourite {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Favourite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Information {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Local {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Local", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Profile {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Running {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Running", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Settings {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_SyncOn {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_SyncOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_32x32_Web {
            get {
                object obj = ResourceManager.GetObject("Image_32x32_Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Add {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Computer {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Edit {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Lock {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Profile {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Roamie {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Roamie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Web {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48x48_Woman {
            get {
                object obj = ResourceManager.GetObject("Image_48x48_Woman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_64x67_Add {
            get {
                object obj = ResourceManager.GetObject("Image_64x67_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_64x67_Favourite {
            get {
                object obj = ResourceManager.GetObject("Image_64x67_Favourite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_64x67_Information {
            get {
                object obj = ResourceManager.GetObject("Image_64x67_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_64x67_Profile {
            get {
                object obj = ResourceManager.GetObject("Image_64x67_Profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_64x67_Settings {
            get {
                object obj = ResourceManager.GetObject("Image_64x67_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_64x67_Web {
            get {
                object obj = ResourceManager.GetObject("Image_64x67_Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cannot be mirrored.
        /// </summary>
        internal static string Information_Caption_CannotMirrorChanges {
            get {
                return ResourceManager.GetString("Information_Caption_CannotMirrorChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roamie&apos;s auto profile was changed.
        /// </summary>
        internal static string Information_Caption_ChangesSaved {
            get {
                return ResourceManager.GetString("Information_Caption_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles found.
        /// </summary>
        internal static string Information_Caption_NoProfilesFound {
            get {
                return ResourceManager.GetString("Information_Caption_NoProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy not supported.
        /// </summary>
        internal static string Information_Caption_ProxyNotSupported {
            get {
                return ResourceManager.GetString("Information_Caption_ProxyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load configuration.
        /// </summary>
        internal static string Information_Caption_UnableToLoadMirandaBootIni {
            get {
                return ResourceManager.GetString("Information_Caption_UnableToLoadMirandaBootIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost.
        /// </summary>
        internal static string Information_Caption_YourChangesWiilBeLost {
            get {
                return ResourceManager.GetString("Information_Caption_YourChangesWiilBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a profile with a download-only provider. Changes made to the local copy of the database cannot be mirrored.[n][n]To publish these changes, choose a profile with an upload-capable provider next time you start Miranda and roam the {0} database..
        /// </summary>
        internal static string Information_Formatable1_Text_CannotMirrorChanges {
            get {
                return ResourceManager.GetString("Information_Formatable1_Text_CannotMirrorChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current database provider does not support HTTP proxy you have configured Roamie with.{0}{0}No proxy settings will be used..
        /// </summary>
        internal static string Information_Formatable1_Text_ProxyNotSupported {
            get {
                return ResourceManager.GetString("Information_Formatable1_Text_ProxyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a profile with a download-only provider. The local copy of the database is set to be removed on exit.[n][n]The changes made to the database will be lost..
        /// </summary>
        internal static string Information_Formatable1_Text_YourChangesWillBeLost {
            get {
                return ResourceManager.GetString("Information_Formatable1_Text_YourChangesWillBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto profile settings have been saved. To see the changes, restart Miranda..
        /// </summary>
        internal static string Information_Text_MirandaBootChangesSaved {
            get {
                return ResourceManager.GetString("Information_Text_MirandaBootChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot configure the default profile when there are no existing roaming profiles..
        /// </summary>
        internal static string Information_Text_NoProfilesFound {
            get {
                return ResourceManager.GetString("Information_Text_NoProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load MirandaBoot.ini, because the file is missing or it is corrupted..
        /// </summary>
        internal static string Information_Text_UnableToLoadMirandaBootIni {
            get {
                return ResourceManager.GetString("Information_Text_UnableToLoadMirandaBootIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string Label_UI_ProfileEditor_MustBeProvided {
            get {
                return ResourceManager.GetString("Label_UI_ProfileEditor_MustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name already exists. Choose a different one..
        /// </summary>
        internal static string Label_UI_ProfileEditor_NameAlreadyExists {
            get {
                return ResourceManager.GetString("Label_UI_ProfileEditor_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a database provider..
        /// </summary>
        internal static string Label_UI_ProfileEditor_NoDbProviderSelected {
            get {
                return ResourceManager.GetString("Label_UI_ProfileEditor_NoDbProviderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile....
        /// </summary>
        internal static string Label_UI_ProfileListView_NewProfile {
            get {
                return ResourceManager.GetString("Label_UI_ProfileListView_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new roaming profile..
        /// </summary>
        internal static string Label_UI_ProfileListView_NewProfile_Description {
            get {
                return ResourceManager.GetString("Label_UI_ProfileListView_NewProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string Label_UI_RoamingStatusDialog_NoProfile {
            get {
                return ResourceManager.GetString("Label_UI_RoamingStatusDialog_NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No synchronization required.
        /// </summary>
        internal static string Label_UI_RoamingStatusDialog_OnExitCHBOX_NoAction {
            get {
                return ResourceManager.GetString("Label_UI_RoamingStatusDialog_OnExitCHBOX_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize remote database.
        /// </summary>
        internal static string Label_UI_RoamingStatusDialog_OnExitCHBOX_Sync {
            get {
                return ResourceManager.GetString("Label_UI_RoamingStatusDialog_OnExitCHBOX_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while applying deltas. Some database changes may not be present.{0}{0}{1}.
        /// </summary>
        internal static string MsgBox_Formatable2Text_ErrorWhileApplyingDeltas {
            get {
                return ResourceManager.GetString("MsgBox_Formatable2Text_ErrorWhileApplyingDeltas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start your e-mail client to write a new message. .
        /// </summary>
        internal static string MsgBox_Text_CannotOpenEmailClient {
            get {
                return ResourceManager.GetString("MsgBox_Text_CannotOpenEmailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the database driver - {0}..
        /// </summary>
        internal static string MsgBox_Text_Formatable1_UnableToLoadDbDriver {
            get {
                return ResourceManager.GetString("MsgBox_Text_Formatable1_UnableToLoadDbDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid host address. Correct or clear the address..
        /// </summary>
        internal static string MsgBox_Text_InvalidHost {
            get {
                return ResourceManager.GetString("MsgBox_Text_InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you have entered is invalid, Roamie cannot be started..
        /// </summary>
        internal static string MsgBox_Text_InvalidMasterKey {
            get {
                return ResourceManager.GetString("MsgBox_Text_InvalidMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete old database and its data? You may lose valuable history and settings..
        /// </summary>
        internal static string MsgBox_Text_LegacyManifestRemoval {
            get {
                return ResourceManager.GetString("MsgBox_Text_LegacyManifestRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile with the selected already exists. Choose a different name..
        /// </summary>
        internal static string MsgBox_Text_ProfileAlreadyExists {
            get {
                return ResourceManager.GetString("MsgBox_Text_ProfileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile created successfully..
        /// </summary>
        internal static string MsgBox_Text_ProfileCreated {
            get {
                return ResourceManager.GetString("MsgBox_Text_ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this profile?.
        /// </summary>
        internal static string MsgBox_Text_ProfileRemovalConfirmation {
            get {
                return ResourceManager.GetString("MsgBox_Text_ProfileRemovalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process start error.
        /// </summary>
        internal static string MsgBox_Title_CannotOpenEmailClient {
            get {
                return ResourceManager.GetString("MsgBox_Title_CannotOpenEmailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string MsgBox_Title_Completed {
            get {
                return ResourceManager.GetString("MsgBox_Title_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta application failed.
        /// </summary>
        internal static string MsgBox_Title_ErrorWhileApplyingDeltas {
            get {
                return ResourceManager.GetString("MsgBox_Title_ErrorWhileApplyingDeltas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host.
        /// </summary>
        internal static string MsgBox_Title_InvalidHost {
            get {
                return ResourceManager.GetString("MsgBox_Title_InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid master key.
        /// </summary>
        internal static string MsgBox_Title_InvalidMasterKey {
            get {
                return ResourceManager.GetString("MsgBox_Title_InvalidMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy manifest removal.
        /// </summary>
        internal static string MsgBox_Title_LegacyManifestRemoval {
            get {
                return ResourceManager.GetString("MsgBox_Title_LegacyManifestRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile already exists.
        /// </summary>
        internal static string MsgBox_Title_ProfileAlreadyExists {
            get {
                return ResourceManager.GetString("MsgBox_Title_ProfileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal confirmation.
        /// </summary>
        internal static string MsgBox_Title_ProfileRemovalConfirmation {
            get {
                return ResourceManager.GetString("MsgBox_Title_ProfileRemovalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver error.
        /// </summary>
        internal static string MsgBox_Title_UnableToLoadDbDriver {
            get {
                return ResourceManager.GetString("MsgBox_Title_UnableToLoadDbDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deltas applied, &quot;Prefer full synchronization&quot; option is recommended..
        /// </summary>
        internal static string Text_Formatable1_UI_RoamingStatus_DeltaMergeRecommended {
            get {
                return ResourceManager.GetString("Text_Formatable1_UI_RoamingStatus_DeltaMergeRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (anonymous).
        /// </summary>
        internal static string Text_UI_Anonymous {
            get {
                return ResourceManager.GetString("Text_UI_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying delta....
        /// </summary>
        internal static string Text_UI_LogText_ApplyingDelta {
            get {
                return ResourceManager.GetString("Text_UI_LogText_ApplyingDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files attached to the remote database could not be retrieved..
        /// </summary>
        internal static string Text_UI_LogText_CannotGetAttachedContainer {
            get {
                return ResourceManager.GetString("Text_UI_LogText_CannotGetAttachedContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Text_UI_LogText_Completed {
            get {
                return ResourceManager.GetString("Text_UI_LogText_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing &amp; encrypting data....
        /// </summary>
        internal static string Text_UI_LogText_CompressingEncrypting {
            get {
                return ResourceManager.GetString("Text_UI_LogText_CompressingEncrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting &amp; decompressing data....
        /// </summary>
        internal static string Text_UI_LogText_DecryptingDecompressing {
            get {
                return ResourceManager.GetString("Text_UI_LogText_DecryptingDecompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes found, beginning delta synchronization....
        /// </summary>
        internal static string Text_UI_LogText_DeltaSyncRequired {
            get {
                return ResourceManager.GetString("Text_UI_LogText_DeltaSyncRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        internal static string Text_UI_LogText_DownloadingDb {
            get {
                return ResourceManager.GetString("Text_UI_LogText_DownloadingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost done....
        /// </summary>
        internal static string Text_UI_LogText_Finishing {
            get {
                return ResourceManager.GetString("Text_UI_LogText_Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting synchronization....
        /// </summary>
        internal static string Text_UI_LogText_Initializing {
            get {
                return ResourceManager.GetString("Text_UI_LogText_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading database manifest....
        /// </summary>
        internal static string Text_UI_LogText_LoadingManifest {
            get {
                return ResourceManager.GetString("Text_UI_LogText_LoadingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes found, delta synchronization skipped..
        /// </summary>
        internal static string Text_UI_LogText_NoDeltaSyncRequired {
            get {
                return ResourceManager.GetString("Text_UI_LogText_NoDeltaSyncRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing delta....
        /// </summary>
        internal static string Text_UI_LogText_PublishingDelta {
            get {
                return ResourceManager.GetString("Text_UI_LogText_PublishingDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing delta manifest....
        /// </summary>
        internal static string Text_UI_LogText_PublishingManifest {
            get {
                return ResourceManager.GetString("Text_UI_LogText_PublishingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing deltas....
        /// </summary>
        internal static string Text_UI_LogText_RemovingDeltas {
            get {
                return ResourceManager.GetString("Text_UI_LogText_RemovingDeltas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving database....
        /// </summary>
        internal static string Text_UI_LogText_Saving {
            get {
                return ResourceManager.GetString("Text_UI_LogText_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === Error ===.
        /// </summary>
        internal static string Text_UI_LogText_SyncFailed {
            get {
                return ResourceManager.GetString("Text_UI_LogText_SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenizing database....
        /// </summary>
        internal static string Text_UI_LogText_TokenizingDb {
            get {
                return ResourceManager.GetString("Text_UI_LogText_TokenizingDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string Text_UI_LogText_Uploading {
            get {
                return ResourceManager.GetString("Text_UI_LogText_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Roamie....
        /// </summary>
        internal static string Text_UI_MenuItem_AboutRoamie {
            get {
                return ResourceManager.GetString("Text_UI_MenuItem_AboutRoamie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaming overview.
        /// </summary>
        internal static string Text_UI_MenuItem_RoamingOverview {
            get {
                return ResourceManager.GetString("Text_UI_MenuItem_RoamingOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A change incompatible with the delta synchronization occured. Full sync is required..
        /// </summary>
        internal static string Text_UI_RoamingStatus_DeltaIncompatibleChange {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_DeltaIncompatibleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delta synchronization WILL BE utilized to synchronize the database..
        /// </summary>
        internal static string Text_UI_RoamingStatus_DeltaSync {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_DeltaSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current database provider DOES NOT support database mirroring..
        /// </summary>
        internal static string Text_UI_RoamingStatus_DownloadOnlySession {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_DownloadOnlySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full synchronization WILL be preferred on exit..
        /// </summary>
        internal static string Text_UI_RoamingStatus_ForceFullSync {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_ForceFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miranda&apos;s local database IS being used..
        /// </summary>
        internal static string Text_UI_RoamingStatus_Local {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miranda&apos;s local database IS prepared for synchronization..
        /// </summary>
        internal static string Text_UI_RoamingStatus_LocalRoaming {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_LocalRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded database WILL remain saved on this computer..
        /// </summary>
        internal static string Text_UI_RoamingStatus_NonPublicMode {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_NonPublicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to the local database WILL be mirrored on the exit..
        /// </summary>
        internal static string Text_UI_RoamingStatus_NonSandboxMode {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_NonSandboxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded database WILL be removed from this computer on exit..
        /// </summary>
        internal static string Text_UI_RoamingStatus_PublicMode {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_PublicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A remote database IS being used..
        /// </summary>
        internal static string Text_UI_RoamingStatus_Roaming {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_Roaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made to the local database WILL NOT be mirrored to the remote one..
        /// </summary>
        internal static string Text_UI_RoamingStatus_SandboxMode {
            get {
                return ResourceManager.GetString("Text_UI_RoamingStatus_SandboxMode", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Watermark_Information {
            get {
                object obj = ResourceManager.GetObject("Watermark_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watermark_Profiles {
            get {
                object obj = ResourceManager.GetObject("Watermark_Profiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watermark_Sync {
            get {
                object obj = ResourceManager.GetObject("Watermark_Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
